In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#

In [3]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2
col = ["name","age","city","salary"]
df2 = pd.DataFrame(data_list,columns = col)
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Inndexing of Columns

In [4]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
df2['name']

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: str

In [6]:
df2['age']

0    28
1    34
2    29
3    42
Name: age, dtype: int64

In [7]:
df2[["name","age"]]

    name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

#Creating a new Columns in DataFrame

In [8]:
#we have to equals number of value that is equal to number of rows otherwise it will give error
df2["Designation"] = ["Doctor","Engineer","Teacher","Scientist"]
df2

    name  age      city  salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000   Scientist

In [9]:
df2.drop("Designation",axis=1)
#it only shows a snapshot of data frame of deletion of the columns it does not remove

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df2

    name  age      city  salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000   Scientist

In [11]:
#for removal of columns completely we have to use inplace = true
df2.drop("Designation",axis=1,inplace=True)

In [12]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selecting Rows

In [13]:
df2.loc[[0,1]]

   name  age      city  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [14]:
df2.iloc[3]

name       Linda
age           42
city      London
salary     85000
Name: 3, dtype: object

Selecting Subset of Rows and Columns

In [15]:
df2.loc[[0,1]][["city","salary"]]

       city  salary
0  New York   65000
1     Paris   70000

In [18]:
df2.loc[[2,3]][["name","age"]]

    name  age
2  Peter   29
3  Linda   42

CONDITIONAL SELECTION

In [19]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
#choose those people their age is more than 30
df2[df2["age"]>30]

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [27]:
#choose those people their age is more than 30 and they belongs to paris
df2[(df2["age"]>30) & (df2["city"]=="Paris")]

   name  age   city  salary
1  Anna   34  Paris   70000